development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: swap_development
  pool: 5
  username:
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: swap_test
  pool: 5
  username:
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: swap_production
  pool: 5
  username:
  password: